/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TaButton {
        /**
          * Set the shape of borders button. Can be set to circle, round or square. If not set, the default value will be set to 'square'
         */
        "shape": string;
        /**
          * Set the type of button. Can be set to primarydasheddanger or omitted (meaning default) If not set, the default value will be set to 'default'
         */
        "type": string;
    }
}
declare global {
    interface HTMLTaButtonElement extends Components.TaButton, HTMLStencilElement {
    }
    var HTMLTaButtonElement: {
        prototype: HTMLTaButtonElement;
        new (): HTMLTaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ta-button": HTMLTaButtonElement;
    }
}
declare namespace LocalJSX {
    interface TaButton {
        /**
          * Set the shape of borders button. Can be set to circle, round or square. If not set, the default value will be set to 'square'
         */
        "shape"?: string;
        /**
          * Set the type of button. Can be set to primarydasheddanger or omitted (meaning default) If not set, the default value will be set to 'default'
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "ta-button": TaButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ta-button": LocalJSX.TaButton & JSXBase.HTMLAttributes<HTMLTaButtonElement>;
        }
    }
}
